import type { Metadata } from "next";
import Widgets from "@/widgets";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Муравей маркет — ИНТЕРНЕТ-МАГАЗИН СТРОИТЕЛЬНЫХ МАТЕРИАЛОВ",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ru">
      <body className="relative bg-neutral-100 antialiased">
        <Widgets.Header />
        <main>{children}</main>
        <Widgets.Footer />
      </body>
    </html>
  );
};

export default RootLayout;
